---
title: "POO - Wooclap Séance 1"
output: html_document
produce:
  html: false
  pdf: false
  moodle: false
  wooclap: true
---

# Wooclap POO - Questions Rapides

---

:::question
id: poo-kahoot-classe
type: schoice
title: Mot-clé pour déclarer une classe

Quel mot-clé déclare une classe en Java ?

:::answers
- [ ] Class
- [x] class
- [ ] new
- [ ] type

:::solution
En Java, le mot-clé `class` (minuscule) permet de déclarer une classe.

---

:::question
id: poo-match-visibilite
type: matching
title: Modificateurs et portées

Associez chaque modificateur à sa portée :

:::answers
- private --- Classe uniquement
- protected --- Classe + sous-classes + package
- public --- Partout
- (rien) --- Package uniquement

:::solution
Les 4 niveaux de visibilité en Java avec leur portée respective.

---

:::question
id: poo-fill-classe
type: cloze
title: Déclaration de classe

Complétez la déclaration de classe :

:::answers
public [class] Voiture [extends] Vehicule { }

:::solution
`class` pour déclarer, `extends` pour hériter.

---

:::question
id: poo-erreur-1
type: schoice
title: Erreur dans le code 1

Quel est le problème dans ce code ?

```java
class Personne {
    private String nom;
}
Personne p = new Personne();
System.out.println(p.nom);
```

:::answers
- [ ] Il manque le mot-clé public
- [x] L'attribut nom est private donc inaccessible
- [ ] Il faut utiliser Personne.nom
- [ ] La classe n'a pas de constructeur

:::solution
L'attribut `nom` est `private`, on ne peut pas y accéder depuis l'extérieur. Il faut un getter.

---

:::question
id: poo-kahoot-new
type: schoice
title: Mot-clé pour créer un objet

Quel mot-clé permet de créer un objet ?

:::answers
- [ ] create
- [ ] object
- [x] new
- [ ] make

:::solution
Le mot-clé `new` permet d'instancier un objet en Java.

---

:::question
id: poo-match-concepts
type: matching
title: Concepts POO et définitions

Associez chaque concept POO à sa définition :

:::answers
- Encapsulation --- Cacher les détails internes
- Héritage --- Réutiliser le code d'une classe parente
- Polymorphisme --- Traiter différents objets via un type commun
- Composition --- Un objet contient d'autres objets

:::solution
Les 4 piliers de la POO et leurs définitions.

---

:::question
id: poo-fill-interface
type: cloze
title: Implémentation d'interface

Complétez l'implémentation d'interface :

:::answers
public class Canard [implements] Volant { }

:::solution
`implements` permet d'implémenter une interface.

---

:::question
id: poo-erreur-2
type: schoice
title: Erreur dans le code 2

Quel est le problème dans ce code ?

```java
abstract class Animal {
    abstract void crier();
}
Animal a = new Animal();
```

:::answers
- [x] On ne peut pas instancier une classe abstraite
- [ ] La méthode crier() n'a pas de corps
- [ ] Il manque le mot-clé public
- [ ] Animal doit être une interface

:::solution
Une classe `abstract` ne peut PAS être instanciée avec `new`.

---

:::question
id: poo-kahoot-private
type: schoice
title: Portée de private

Un attribut `private` est accessible depuis...

:::answers
- [x] Sa propre classe uniquement
- [ ] Toutes les classes
- [ ] Les classes filles
- [ ] Le même package

:::solution
`private` limite l'accès à la classe elle-même.

---

:::question
id: poo-match-motsclés
type: matching
title: Mots-clés et usages

Associez chaque mot-clé à son usage :

:::answers
- extends --- Hériter d'une classe
- implements --- Implémenter une interface
- super --- Appeler le parent
- this --- Référencer l'objet courant

:::solution
Les mots-clés essentiels de la POO Java.

---

:::question
id: poo-fill-constructeur
type: cloze
title: Constructeur avec this

Complétez le constructeur :

:::answers
public Personne(String nom) { [this].nom = nom; }

:::solution
`this` distingue l'attribut du paramètre.

---

:::question
id: poo-erreur-3
type: schoice
title: Erreur dans le code 3

Quel est le problème dans ce code ?

```java
class Voiture extends Vehicule {
    public Voiture(String marque) {
        this.marque = marque;
    }
}
```

:::answers
- [ ] Il faut utiliser extends autrement
- [ ] this.marque est incorrect
- [x] Il faut appeler super() en premier
- [ ] Le constructeur doit être private

:::solution
Le constructeur de la classe parente doit être appelé en premier avec `super(marque)`.

---

:::question
id: poo-kahoot-heritage
type: schoice
title: Mot-clé pour hériter

Quel mot-clé permet d'hériter d'une classe ?

:::answers
- [ ] inherits
- [ ] implements
- [x] extends
- [ ] super

:::solution
`extends` permet d'hériter d'une classe parente.

---

:::question
id: poo-match-methodes
type: matching
title: Méthodes Object et rôles

Associez chaque méthode Object à son rôle :

:::answers
- equals() --- Comparer le contenu
- toString() --- Représentation textuelle
- hashCode() --- Code de hachage
- getClass() --- Obtenir le type

:::solution
Méthodes héritées de Object utilisées fréquemment.

---

:::question
id: poo-fill-heritage
type: cloze
title: Appel au constructeur parent

Complétez l'appel au constructeur parent :

:::answers
public Voiture(String marque) { [super](marque); }

:::solution
`super(...)` appelle le constructeur de la classe parente.

---

:::question
id: poo-erreur-4
type: schoice
title: Erreur dans le code 4

Quel est le problème dans ce code ?

```java
String a = "hello";
String b = "hello";
if (a == b) {
    System.out.println("égaux");
}
```

:::answers
- [ ] Il faut utiliser a.compareTo(b)
- [x] Il faut utiliser a.equals(b) pour comparer le contenu
- [ ] Les String ne peuvent pas être comparés
- [ ] Il manque des accolades

:::solution
`==` compare les références, pas le contenu. Pour comparer le contenu de deux objets, utiliser `equals()`.

---

:::question
id: poo-kahoot-interface
type: schoice
title: Mot-clé pour implémenter

Quel mot-clé permet d'implémenter une interface ?

:::answers
- [ ] extends
- [x] implements
- [ ] interface
- [ ] uses

:::solution
`implements` permet d'implémenter une interface.

---

:::question
id: poo-match-relations
type: matching
title: Relations UML et exemples

Associez chaque relation UML à son exemple :

:::answers
- Est-un --- Voiture extends Vehicule
- A-un --- Voiture contient Moteur
- Utilise --- Conducteur utilise Voiture
- Implémente --- Canard implements Volant

:::solution
Les différentes relations entre classes en POO.

---

:::question
id: poo-fill-getter
type: cloze
title: Getter

Complétez le getter :

:::answers
public String getNom() { [return] this.nom; }

:::solution
Un getter utilise `return` pour retourner la valeur.

---

:::question
id: poo-erreur-5
type: schoice
title: Erreur dans le code 5

Quel est le problème dans ce code ?

```java
interface Volant {
    void voler() {
        System.out.println("Je vole");
    }
}
```

:::answers
- [ ] Il faut utiliser class au lieu de interface
- [x] Une méthode d'interface ne peut pas avoir de corps (sauf default)
- [ ] void n'est pas autorisé dans une interface
- [ ] Il manque le mot-clé public

:::solution
Les méthodes d'interface sont abstraites par défaut. Pour avoir un corps, il faut utiliser `default void voler()`.

---

:::question
id: poo-kahoot-this
type: schoice
title: Mot-clé this

À quoi sert le mot-clé `this` ?

:::answers
- [ ] Créer un objet
- [x] Référencer l'objet courant
- [ ] Appeler le parent
- [ ] Déclarer une variable

:::solution
`this` fait référence à l'instance courante de la classe.

---

:::question
id: poo-match-erreurs
type: matching
title: Erreurs et causes

Associez chaque erreur à sa cause probable :

:::answers
- NullPointerException --- Appel de méthode sur null
- StackOverflowError --- Récursion infinie
- ClassCastException --- Cast impossible entre types
- ArrayIndexOutOfBoundsException --- Index hors limites

:::solution
Les erreurs courantes en Java et leurs causes.

---

:::question
id: poo-fill-instanciation
type: cloze
title: Création d'objet

Complétez la création d'objet :

:::answers
Voiture v = [new] Voiture("Peugeot");

:::solution
`new` permet d'instancier un objet.

---

:::question
id: poo-erreur-6
type: schoice
title: Erreur dans le code 6

Quel est le problème dans ce code ?

```java
class Enfant extends Parent {
    @Override
    public void methode(int x) { }
}
class Parent {
    public void methode(String s) { }
}
```

:::answers
- [ ] @Override est mal placé
- [x] La signature ne correspond pas (int vs String) donc ce n'est pas une redéfinition
- [ ] On ne peut pas hériter de Parent
- [ ] Il faut utiliser super.methode()

:::solution
Pour redéfinir une méthode, la signature doit être identique. Ici c'est une surcharge, pas une redéfinition.

---

:::question
id: poo-kahoot-super
type: schoice
title: Mot-clé super

À quoi sert le mot-clé `super` ?

:::answers
- [ ] Créer un objet
- [ ] Référencer l'objet courant
- [x] Appeler le parent
- [ ] Déclarer une variable

:::solution
`super` permet d'accéder aux membres de la classe parente.

---

:::question
id: poo-match-types
type: matching
title: Types et valeurs par défaut

Associez chaque type à sa valeur par défaut :

:::answers
- int --- 0
- boolean --- false
- String --- null
- double --- 0.0

:::solution
Les valeurs par défaut des types primitifs et objets en Java.

---

:::question
id: poo-fill-override
type: cloze
title: Redéfinition de méthode

Complétez la redéfinition de méthode :

:::answers
[@Override] public String toString() { return this.nom; }

:::solution
`@Override` indique qu'on redéfinit une méthode héritée.

---

:::question
id: poo-erreur-7
type: schoice
title: Erreur dans le code 7

Quel est le problème dans ce code ?

```java
public class Test {
    private int valeur = 10;
    
    public static void afficher() {
        System.out.println(valeur);
    }
}
```

:::answers
- [ ] valeur doit être public
- [ ] Il manque un constructeur
- [x] Une méthode static ne peut pas accéder à un attribut non-static
- [ ] println ne peut pas afficher un int

:::solution
Les méthodes `static` n'ont pas accès aux attributs d'instance. Il faut soit rendre `valeur` static, soit rendre la méthode non-static.

---

:::question
id: poo-kahoot-null
type: schoice
title: Référence non initialisée

Que vaut une référence non initialisée ?

:::answers
- [ ] 0
- [ ] ""
- [x] null
- [ ] undefined

:::solution
Une référence non initialisée vaut `null` en Java.

---

:::question
id: poo-match-modificateurs
type: matching
title: Modificateurs et effets

Associez chaque modificateur à son effet :

:::answers
- final (classe) --- Ne peut pas être héritée
- final (méthode) --- Ne peut pas être redéfinie
- final (variable) --- Ne peut pas être modifiée
- abstract --- Doit être implémentée

:::solution
Le mot-clé `final` a différents effets selon le contexte.

---

:::question
id: poo-fill-setter
type: cloze
title: Setter

Complétez le setter :

:::answers
public void setNom(String nom) { [this].nom = nom; }

:::solution
Un setter modifie la valeur d'un attribut.

---

:::question
id: poo-erreur-8
type: schoice
title: Erreur dans le code 8

Quel est le problème dans ce code ?

```java
List<Animal> animaux = new ArrayList<>();
animaux.add(new Chien());
Chien c = animaux.get(0);
```

:::answers
- [ ] ArrayList ne peut pas contenir d'Animal
- [ ] add() ne fonctionne pas avec Chien
- [x] Il faut caster : (Chien) animaux.get(0)
- [ ] get(0) retourne null

:::solution
`animaux.get(0)` retourne un `Animal`, pas un `Chien`. Il faut un cast explicite.

---

:::question
id: poo-kahoot-getter
type: schoice
title: Méthode qui retourne un attribut

Comment nomme-t-on une méthode qui retourne un attribut ?

:::answers
- [x] Getter
- [ ] Setter
- [ ] Accessor
- [ ] Reader

:::solution
Un getter (ou accesseur) retourne la valeur d'un attribut.

---

:::question
id: poo-match-collections
type: matching
title: Collections et caractéristiques

Associez chaque collection à sa caractéristique :

:::answers
- List --- Éléments ordonnés avec doublons
- Set --- Éléments uniques sans ordre
- Map --- Paires clé-valeur
- Queue --- Premier entré premier sorti

:::solution
Les principales collections Java et leurs caractéristiques.

---

:::question
id: poo-fill-abstract
type: cloze
title: Classe abstraite

Complétez la déclaration de classe abstraite :

:::answers
public [abstract] class Animal { [abstract] void crier(); }

:::solution
`abstract` rend une classe ou méthode abstraite.

---

:::question
id: poo-erreur-9
type: schoice
title: Erreur dans le code 9

Quel est le problème dans ce code ?

```java
public class Cercle {
    private final double rayon;
    
    public void setRayon(double r) {
        this.rayon = r;
    }
}
```

:::answers
- [ ] rayon doit être public
- [x] Un attribut final ne peut pas être modifié après initialisation
- [ ] Il faut un getter avant le setter
- [ ] double n'accepte pas les décimaux

:::solution
Un attribut `final` ne peut être assigné qu'une fois (dans le constructeur ou à la déclaration).

---

:::question
id: poo-kahoot-abstract
type: schoice
title: Instanciation d'une classe abstraite

Une classe `abstract` peut-elle être instanciée ?

:::answers
- [ ] Oui toujours
- [x] Non jamais
- [ ] Seulement avec new
- [ ] Seulement dans main()

:::solution
Une classe abstraite ne peut PAS être instanciée directement.

---

:::question
id: poo-match-heritage
type: matching
title: Héritage et mots-clés

Associez chaque situation à l'utilisation correcte :

:::answers
- Classe hérite de classe --- extends
- Classe implémente interface --- implements
- Interface hérite d'interface --- extends
- Appel méthode parent --- super.methode()

:::solution
Les différentes formes d'héritage en Java.

---

:::question
id: poo-fill-interface-impl
type: cloze
title: Interface avec méthode

Complétez l'interface :

:::answers
public interface Comparable { int [compareTo](Object o); }

:::solution
Une interface définit des signatures de méthodes.

---

:::question
id: poo-erreur-10
type: schoice
title: Erreur dans le code 10

Quel est le problème dans ce code ?

```java
class A { }
class B extends A { }
class C extends A { }

B b = new B();
C c = (C) b;
```

:::answers
- [ ] B et C ne peuvent pas hériter de A
- [ ] Le cast (C) est syntaxiquement incorrect
- [x] B ne peut pas être casté en C (ClassCastException)
- [ ] Il faut utiliser instanceof

:::solution
B et C sont des classes sœurs, pas dans une relation d'héritage direct. Le cast échouera à l'exécution.

---

:::question
id: poo-kahoot-equals
type: schoice
title: Comparaison de contenu

Quelle méthode compare le contenu de deux objets ?

:::answers
- [ ] ==
- [x] equals()
- [ ] compare()
- [ ] same()

:::solution
`equals()` compare le contenu, `==` compare les références.

---

:::question
id: poo-match-constructeur
type: matching
title: Constructeurs et règles

Associez chaque situation à la règle :

:::answers
- Pas de constructeur défini --- Java crée un constructeur par défaut
- super() non appelé --- Java l'ajoute implicitement
- this() en premier --- Appelle un autre constructeur de la même classe
- Constructeur privé --- Empêche l'instanciation externe

:::solution
Les règles importantes sur les constructeurs.

---

:::question
id: poo-fill-polymorphisme
type: cloze
title: Polymorphisme

Complétez le code polymorphe :

:::answers
Animal a = new [Chien](); a.[aboyer]();

:::solution
Le polymorphisme permet de manipuler un objet via son type parent.

---

:::question
id: poo-kahoot-encapsulation
type: schoice
title: Principe d'encapsulation

L'encapsulation consiste à...

:::answers
- [x] Cacher les détails internes
- [ ] Hériter d'une classe
- [ ] Créer plusieurs objets
- [ ] Utiliser des interfaces

:::solution
L'encapsulation cache l'implémentation et expose une interface publique.

---

:::question
id: poo-match-poo-principes
type: matching
title: Principes POO et exemples

Associez chaque principe à son exemple :

:::answers
- Encapsulation --- Attributs private + getters/setters
- Héritage --- class Chien extends Animal
- Polymorphisme --- Animal a = new Chien()
- Abstraction --- interface Comparable

:::solution
Les principes fondamentaux de la POO avec des exemples concrets.

---

:::question
id: poo-fill-exception
type: cloze
title: Gestion d'exception

Complétez la gestion d'exception :

:::answers
[try] { risque(); } [catch](Exception e) { traiter(); }

:::solution
`try`/`catch` permet de gérer les exceptions.

---

:::question
id: poo-kahoot-polymorphisme
type: schoice
title: Principe du polymorphisme

Le polymorphisme permet...

:::answers
- [ ] De créer des classes
- [ ] D'avoir des attributs privés
- [x] D'utiliser un même type pour différents objets
- [ ] De définir des constantes

:::solution
Le polymorphisme permet de traiter différents objets via un type commun.

---

:::question
id: poo-fill-instanceof
type: cloze
title: Vérification de type

Complétez la vérification de type :

:::answers
if (animal [instanceof] Chien) { Chien c = (Chien) animal; }

:::solution
`instanceof` vérifie le type réel d'un objet avant un cast.

---

:::question
id: poo-match-static
type: matching
title: Static vs Instance

Associez chaque caractéristique au bon type :

:::answers
- Partagé par toutes les instances --- static
- Propre à chaque objet --- instance
- Accessible sans créer d'objet --- static
- Nécessite this --- instance

:::solution
Différences entre membres statiques et d'instance.
